# Generated by Django 3.0.5 on 2020-04-12 06:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('api_key', models.CharField(max_length=256)),
                ('check_type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=8)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[], max_length=8)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=8)),
                ('pdf_file', models.FileField(upload_to='')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='app.Printer')),
            ],
        ),
    ]
