# Generated by Django 3.0.5 on 2020-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200412_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=8),
        ),
    ]
